# Generated by Django 3.1.4 on 2020-12-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url_hash', models.CharField(max_length=30, unique=True)),
                ('url', models.TextField(max_length=100)),
            ],
        ),
    ]
