# Generated by Django 3.1.4 on 2020-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='url',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
